# Generated by Django 4.2.5 on 2023-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('BR', 'Bradesco'), ('IT', 'Itaú'), ('BB', 'Banco do Brasil')], max_length=2),
        ),
    ]
