# Generated by Django 4.2.5 on 2023-09-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0002_alter_valores_categoria_alter_valores_conta'),
        ('perfil', '0002_alter_conta_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.conta')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrato.valores')),
            ],
        ),
    ]
