# Generated by Django 4.2.5 on 2023-09-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_salario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='conta',
        ),
        migrations.AlterField(
            model_name='salario',
            name='valor',
            field=models.FloatField(),
        ),
    ]
